version: '3.7'
services: 
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: elearning-industry-app
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0.26
    container_name: elearning-industry-mysql
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .docker/mysql/.env
    volumes:
      - .docker/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ~/Workspaces/mysql/db:/var/lib/mysql
